create table endpoint (id varchar(255) not null, editable_state varchar, type varchar(255), primary key (id))
create table endpoint_job (id bigint generated by default as identity, expected_to_finish timestamp, expected_to_start timestamp, finished timestamp, params varchar, started timestamp, endpoint_id varchar(255) not null, program_id bigint, primary key (id))
create table endpoint_program (id bigint generated by default as identity, description varchar(255), name varchar(255), parameter_scheme varchar, endpoint_id varchar(255) not null, primary key (id))
alter table endpoint_job add constraint FKj99fiw0hfa7gn4ywfb9wk17yf foreign key (endpoint_id) references endpoint
alter table endpoint_job add constraint FKererv2jjd1pwdr6ra8a9k11ed foreign key (program_id) references endpoint_program
alter table endpoint_program add constraint FKjc7djmk25mc54jb1c32lvc9nx foreign key (endpoint_id) references endpoint
